try:
    n=int(input())
    if(n<=1000):
        r=rev=0
        nn=n
        while(n>0):
            r=n%10
            rev=r+rev*10
            n=n//10
        if(nn==rev):
            print('yes')
        else:
            print('no')
    else:
        print('invalid')
except:
    print('invalid')
